---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - JELLYFIN_PublishedServerUrl=http://192.168.0.33 #optional
    volumes:
      - /docker/jellyfin:/config
      - /data:/data
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Brussels
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /docker/jellyseerr:/app/config
    restart: unless-stopped